/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package mini;

public @SuppressWarnings("all") interface MiniJavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int LSQPAREN = 11;
  int RSQPAREN = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int SEMICOLON = 15;
  int DOT = 16;
  int ASSIGN = 17;
  int LT = 18;
  int PLUS = 19;
  int MINUS = 20;
  int AND = 21;
  int NOT = 22;
  int DIV = 23;
  int MOD = 24;
  int GT = 25;
  int EQU = 26;
  int NEQU = 27;
  int GEQU = 28;
  int SEQU = 29;
  int OR = 30;
  int BOOLEAN = 31;
  int INTEGER = 32;
  int PUBLIC = 33;
  int VOID = 34;
  int STATIC = 35;
  int MAIN = 36;
  int STRING = 37;
  int MESSAGEHANDLER = 38;
  int MINIDRAW = 39;
  int FINAL = 40;
  int CLASS = 41;
  int EXTENDS = 42;
  int RETURN = 43;
  int IF = 44;
  int ELSE = 45;
  int WHILE = 46;
  int PRINT = 47;
  int LENGTH = 48;
  int NEW = 49;
  int THIS = 50;
  int TRUE = 51;
  int FALSE = 52;
  int INTEGER_LITERAL = 53;
  int IDENTIFIER = 54;
  int LETTER = 55;
  int DIGIT = 56;
  int CHAR_LITERAL = 57;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"&&\"",
    "\"!\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"||\"",
    "\"boolean\"",
    "\"int\"",
    "\"public\"",
    "\"void\"",
    "\"static\"",
    "\"main\"",
    "\"String\"",
    "\"MessageHandler\"",
    "\"MiniDraw\"",
    "\"final\"",
    "\"class\"",
    "\"extends\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"length\"",
    "\"new\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<CHAR_LITERAL>",
    "\",\"",
    "\"Minijava.print\"",
    "\"Minijava.scanf\"",
    "\"Minijava.present\"",
    "\"Minijava.srand\"",
    "\"Minijava.rand\"",
    "\"Minijava.window\"",
    "\"Minijava.wait\"",
    "\"Minijava.getkey\"",
    "\"Minijava.color\"",
    "\"Minijava.bitblt\"",
    "\"*\"",
  };

}
