//
// Generated by JTB 1.3.2
//

package mini.visitor;
import mini.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public @SuppressWarnings("all") class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * mainClass -> MainClass()
    * nodeListOptional -> ( ClassDecl() )*
    * nodeOptional -> ( DrawClass() )?
    * nodeListOptional1 -> ( ClassDecl() )*
    * nodeToken -> <EOF>
    */
   public void visit(Program n) {
      n.mainClass.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeToken2 -> "public"
    * nodeToken3 -> "static"
    * nodeToken4 -> "void"
    * nodeToken5 -> "main"
    * nodeToken6 -> "("
    * nodeToken7 -> "String"
    * nodeToken8 -> "["
    * nodeToken9 -> "]"
    * identifier1 -> Identifier()
    * nodeToken10 -> ")"
    * nodeToken11 -> "{"
    * ioStatement -> IoStatement()
    * nodeToken12 -> "}"
    * nodeToken13 -> "}"
    */
   public void visit(MainClass n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
      n.nodeToken8.accept(this);
      n.nodeToken9.accept(this);
      n.identifier1.accept(this);
      n.nodeToken10.accept(this);
      n.nodeToken11.accept(this);
      n.ioStatement.accept(this);
      n.nodeToken12.accept(this);
      n.nodeToken13.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "extends"
    * nodeToken2 -> "MiniDraw"
    * nodeToken3 -> "{"
    * nodeListOptional -> ( VarDecl() )*
    * nodeListOptional1 -> ( MethodDecl() )*
    * messageHandler -> MessageHandler()
    * nodeListOptional2 -> ( MethodDecl() )*
    * nodeToken4 -> "}"
    */
   public void visit(DrawClass n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.messageHandler.accept(this);
      n.nodeListOptional2.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "final"
    * nodeToken2 -> "int"
    * nodeToken3 -> "MessageHandler"
    * nodeToken4 -> "("
    * arrayType -> ArrayType()
    * identifier -> Identifier()
    * nodeToken5 -> ","
    * integerType -> IntegerType()
    * identifier1 -> Identifier()
    * nodeToken6 -> ")"
    * nodeToken7 -> "{"
    * nodeListOptional -> ( VarDecl() )*
    * nodeListOptional1 -> ( Statement() )*
    * nodeToken8 -> "return"
    * exp -> Exp()
    * nodeToken9 -> ";"
    * nodeToken10 -> "}"
    */
   public void visit(MessageHandler n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.arrayType.accept(this);
      n.identifier.accept(this);
      n.nodeToken5.accept(this);
      n.integerType.accept(this);
      n.identifier1.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeToken8.accept(this);
      n.exp.accept(this);
      n.nodeToken9.accept(this);
      n.nodeToken10.accept(this);
   }

   /**
    * nodeChoice -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public void visit(ClassDecl n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( VarDecl() )*
    * nodeListOptional1 -> ( MethodDecl() )*
    * nodeToken2 -> "}"
    */
   public void visit(ClassDeclaration n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "extends"
    * identifier1 -> Identifier()
    * nodeToken2 -> "{"
    * nodeListOptional -> ( VarDecl() )*
    * nodeListOptional1 -> ( MethodDecl() )*
    * nodeToken3 -> "}"
    */
   public void visit(ClassExtendsDeclaration n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.identifier1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken -> ";"
    */
   public void visit(VarDecl n) {
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "public"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalList() )?
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * nodeListOptional -> ( VarDecl() )*
    * nodeListOptional1 -> ( Statement() )*
    * nodeToken4 -> "return"
    * exp -> Exp()
    * nodeToken5 -> ";"
    * nodeToken6 -> "}"
    */
   public void visit(MethodDecl n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeToken4.accept(this);
      n.exp.accept(this);
      n.nodeToken5.accept(this);
      n.nodeToken6.accept(this);
   }

   /**
    * formalParameter -> FormalParameter()
    * nodeListOptional -> ( FormalRest() )*
    */
   public void visit(FormalList n) {
      n.formalParameter.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(FormalParameter n) {
      n.type.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> ","
    * formalParameter -> FormalParameter()
    */
   public void visit(FormalRest n) {
      n.nodeToken.accept(this);
      n.formalParameter.accept(this);
   }

   /**
    * nodeChoice -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public void visit(Type n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "int"
    * nodeToken1 -> "["
    * nodeToken2 -> "]"
    */
   public void visit(ArrayType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "boolean"
    */
   public void visit(BooleanType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "int"
    */
   public void visit(IntegerType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | ExpStatement()
    *       | IoStatement()
    *       | GuiStatement()
    */
   public void visit(Statement n) {
      n.nodeChoice.accept(this);
   }

   /**
    * exp -> Exp()
    * nodeToken -> ";"
    */
   public void visit(ExpStatement n) {
      n.exp.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "{"
    * nodeListOptional -> ( Statement() )*
    * nodeToken1 -> "}"
    */
   public void visit(Block n) {
      n.nodeToken.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "="
    * exp -> Exp()
    * nodeToken1 -> ";"
    */
   public void visit(AssignmentStatement n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.exp.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * exp -> Exp()
    * nodeToken1 -> "]"
    * nodeToken2 -> "="
    * exp1 -> Exp()
    * nodeToken3 -> ";"
    */
   public void visit(ArrayAssignmentStatement n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.exp.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.exp1.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "if"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ")"
    * statement -> Statement()
    * nodeOptional -> [ ElseStatement() ]
    */
   public void visit(IfStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.statement.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * nodeToken -> "else"
    * statement -> Statement()
    */
   public void visit(ElseStatement n) {
      n.nodeToken.accept(this);
      n.statement.accept(this);
   }

   /**
    * nodeToken -> "while"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ")"
    * statement -> Statement()
    */
   public void visit(WhileStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.statement.accept(this);
   }

   /**
    * nodeChoice -> Println()
    *       | Print()
    *       | Read()
    */
   public void visit(IoStatement n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "System.out.println"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(Println n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "Minijava.print"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(Print n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "Minijava.scanf"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(Read n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeChoice -> Window()
    *       | Wait()
    *       | GetKeyState()
    *       | Color()
    *       | Bitblt()
    *       | Present()
    *       | Srand()
    *       | Rand()
    */
   public void visit(GuiStatement n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "Minijava.present"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ","
    * exp1 -> Exp()
    * nodeToken3 -> ")"
    * nodeToken4 -> ";"
    */
   public void visit(Present n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.exp1.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Minijava.srand"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(Srand n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "Minijava.rand"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(Rand n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "Minijava.window"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ","
    * exp1 -> Exp()
    * nodeToken3 -> ","
    * exp2 -> Exp()
    * nodeToken4 -> ","
    * exp3 -> Exp()
    * nodeToken5 -> ")"
    * nodeToken6 -> ";"
    */
   public void visit(Window n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.exp1.accept(this);
      n.nodeToken3.accept(this);
      n.exp2.accept(this);
      n.nodeToken4.accept(this);
      n.exp3.accept(this);
      n.nodeToken5.accept(this);
      n.nodeToken6.accept(this);
   }

   /**
    * nodeToken -> "Minijava.wait"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(Wait n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "Minijava.getkey"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ","
    * identifier -> Identifier()
    * nodeToken3 -> ")"
    * nodeToken4 -> ";"
    */
   public void visit(GetKeyState n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.identifier.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Minijava.color"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ","
    * exp1 -> Exp()
    * nodeToken3 -> ","
    * exp2 -> Exp()
    * nodeToken4 -> ","
    * exp3 -> Exp()
    * nodeToken5 -> ","
    * identifier -> Identifier()
    * nodeToken6 -> ")"
    * nodeToken7 -> ";"
    */
   public void visit(Color n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.exp1.accept(this);
      n.nodeToken3.accept(this);
      n.exp2.accept(this);
      n.nodeToken4.accept(this);
      n.exp3.accept(this);
      n.nodeToken5.accept(this);
      n.identifier.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
   }

   /**
    * nodeToken -> "Minijava.bitblt"
    * nodeToken1 -> "("
    * exp -> Exp()
    * nodeToken2 -> ","
    * exp1 -> Exp()
    * nodeToken3 -> ","
    * exp2 -> Exp()
    * nodeToken4 -> ","
    * exp3 -> Exp()
    * nodeToken5 -> ","
    * exp4 -> Exp()
    * nodeToken6 -> ")"
    * nodeToken7 -> ";"
    */
   public void visit(Bitblt n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.exp.accept(this);
      n.nodeToken2.accept(this);
      n.exp1.accept(this);
      n.nodeToken3.accept(this);
      n.exp2.accept(this);
      n.nodeToken4.accept(this);
      n.exp3.accept(this);
      n.nodeToken5.accept(this);
      n.exp4.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
   }

   /**
    * nodeChoice -> AndExpression()
    *       | OrExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ModExpression()
    *       | CompareBigExpression()
    *       | CompareEquExpression()
    *       | CompareNotEquExpression()
    *       | CompareBigEquExpression()
    *       | CompareSmallEquExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public void visit(Exp n) {
      n.nodeChoice.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "/"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(DivExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "%"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(ModExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> ">"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareBigExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "=="
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareEquExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "!="
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareNotEquExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> ">="
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareBigEquExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "<="
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareSmallEquExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "||"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(OrExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "&&"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(AndExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "<"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "+"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(PlusExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "-"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(MinusExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "*"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(TimesExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "["
    * primaryExpression1 -> PrimaryExpression()
    * nodeToken1 -> "]"
    */
   public void visit(ArrayLookup n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * nodeToken1 -> "length"
    */
   public void visit(ArrayLength n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( ExpList() )?
    * nodeToken2 -> ")"
    */
   public void visit(MessageSend n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * exp -> Exp()
    * nodeListOptional -> ( ExpRest() )*
    */
   public void visit(ExpList n) {
      n.exp.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * nodeToken -> ","
    * exp -> Exp()
    */
   public void visit(ExpRest n) {
      n.nodeToken.accept(this);
      n.exp.accept(this);
   }

   /**
    * nodeChoice -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    *       | CharLiteral()
    */
   public void visit(PrimaryExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <CHAR_LITERAL>
    */
   public void visit(CharLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "true"
    */
   public void visit(TrueLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "false"
    */
   public void visit(FalseLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "this"
    */
   public void visit(ThisExpression n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "new"
    * nodeToken1 -> "int"
    * nodeToken2 -> "["
    * exp -> Exp()
    * nodeToken3 -> "]"
    */
   public void visit(ArrayAllocationExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.exp.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "new"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeToken2 -> ")"
    */
   public void visit(AllocationExpression n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "!"
    * exp -> Exp()
    */
   public void visit(NotExpression n) {
      n.nodeToken.accept(this);
      n.exp.accept(this);
   }

   /**
    * nodeToken -> "("
    * exp -> Exp()
    * nodeToken1 -> ")"
    */
   public void visit(BracketExpression n) {
      n.nodeToken.accept(this);
      n.exp.accept(this);
      n.nodeToken1.accept(this);
   }

}
