//
// Generated by JTB 1.3.2
//

package mini.syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "."
 * nodeToken1 -> "length"
 */
public @SuppressWarnings("all") class ArrayLength implements Node {
   private Node parent;
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;

   public ArrayLength(PrimaryExpression n0, NodeToken n1, NodeToken n2) {
      primaryExpression = n0;
      if ( primaryExpression != null ) primaryExpression.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n2;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
   }

   public ArrayLength(PrimaryExpression n0) {
      primaryExpression = n0;
      if ( primaryExpression != null ) primaryExpression.setParent(this);
      nodeToken = new NodeToken(".");
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = new NodeToken("length");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
   }

   public void accept(mini.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(mini.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(mini.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(mini.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

