//
// Generated by JTB 1.3.2
//

package mini.syntaxtree;

/**
 * Grammar production:
 * identifier -> Identifier()
 * nodeToken -> "="
 * exp -> Exp()
 * nodeToken1 -> ";"
 */
public @SuppressWarnings("all") class AssignmentStatement implements Node {
   private Node parent;
   public Identifier identifier;
   public NodeToken nodeToken;
   public Exp exp;
   public NodeToken nodeToken1;

   public AssignmentStatement(Identifier n0, NodeToken n1, Exp n2, NodeToken n3) {
      identifier = n0;
      if ( identifier != null ) identifier.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n2;
      if ( exp != null ) exp.setParent(this);
      nodeToken1 = n3;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
   }

   public AssignmentStatement(Identifier n0, Exp n1) {
      identifier = n0;
      if ( identifier != null ) identifier.setParent(this);
      nodeToken = new NodeToken("=");
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n1;
      if ( exp != null ) exp.setParent(this);
      nodeToken1 = new NodeToken(";");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
   }

   public void accept(mini.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(mini.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(mini.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(mini.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

