//
// Generated by JTB 1.3.2
//

package mini.syntaxtree;

/**
 * Grammar production:
 * exp -> Exp()
 * nodeListOptional -> ( ExpRest() )*
 */
public @SuppressWarnings("all") class ExpList implements Node {
   private Node parent;
   public Exp exp;
   public NodeListOptional nodeListOptional;

   public ExpList(Exp n0, NodeListOptional n1) {
      exp = n0;
      if ( exp != null ) exp.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(mini.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(mini.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(mini.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(mini.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

