//
// Generated by JTB 1.3.2
//

package mini.syntaxtree;

/**
 * Grammar production:
 * exp -> Exp()
 * nodeToken -> ";"
 */
public @SuppressWarnings("all") class ExpStatement implements Node {
   private Node parent;
   public Exp exp;
   public NodeToken nodeToken;

   public ExpStatement(Exp n0, NodeToken n1) {
      exp = n0;
      if ( exp != null ) exp.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
   }

   public ExpStatement(Exp n0) {
      exp = n0;
      if ( exp != null ) exp.setParent(this);
      nodeToken = new NodeToken(";");
      if ( nodeToken != null ) nodeToken.setParent(this);
   }

   public void accept(mini.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(mini.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(mini.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(mini.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

