//
// Generated by JTB 1.3.2
//

package mini.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> ","
 * formalParameter -> FormalParameter()
 */
public @SuppressWarnings("all") class FormalRest implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public FormalParameter formalParameter;

   public FormalRest(NodeToken n0, FormalParameter n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      formalParameter = n1;
      if ( formalParameter != null ) formalParameter.setParent(this);
   }

   public FormalRest(FormalParameter n0) {
      nodeToken = new NodeToken(",");
      if ( nodeToken != null ) nodeToken.setParent(this);
      formalParameter = n0;
      if ( formalParameter != null ) formalParameter.setParent(this);
   }

   public void accept(mini.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(mini.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(mini.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(mini.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

